name: Image Conversion

on:
  workflow_dispatch:
    inputs:
      conversion_trigger:
        description: 'Trigger for image conversion'
        default: 'true'
        required: true
        type: string

jobs:
  convert-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean up /usr/lib/python3.10 (if needed)
      run: echo "No cleanup needed for GitHub Actions environment."

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml
        activate-environment: base

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Convert images
      run: python convert_images.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add setup-miniconda-patched-environment.yml
        git add webp/100px
        git add webp/512px
        git commit -m "Add converted images"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          webp/*.webp
        tag_name: v${{ github.run_id }}
        release_name: Release v${{ github.run_id }}
        body: |
          Release generated from job ID: ${{ github.run_id }}
